spring.application.name=mobiles
spring.data.mongodb.uri=mongodb://localhost:27017/mobiles
reddit.client.id=VTAVt6k7g-H6nMZfc3QTpA
reddit.client.secret=BtAHgg9JEclM3DdTvfbKkMsKvhjB-A
reddit.username=Lonely-One180
reddit.password=Reddit#427
spring.ai.anthropic.api-key=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
spring.ai.anthropic.chat.options.model=claude-3-5-sonnet-latest
server.port=8080
